# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy package files and install dependencies (cache layer)
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy all source files
COPY . .

# Build the project
RUN pnpm run build

# Install this package globally so that the 'figma-mcp' command is available
RUN npm install -g .

# Expose the port (default 3333)
EXPOSE 3333

# Default command to run the MCP server
CMD [ "figma-mcp", "--stdio" ]
